### ISSUE TITLE
Gem not available on Rubygems

### ISSUE THREAD

**Issue by choilive** [ratdaddy/immigrate#1]
Immigrate doesn't seem to be available on rubygems.org. Not sure if this was intended or not.

**Comment by ratdaddy** [comment]
I wanted to implement some more basic functionality before first releasing it. I also want to make sure there is no conflict for the name so I have now released it to rubygems.org

**Comment by choilive** [comment]
Ah, I guess I was a bit early to the party. I would love to contribute, is there a todo list somewhere of features you are planning on implementing?
